title: Francisco Garrido-Valenzuela
email: ""  # Optional, or you can add your email here
description: >-
  I’m an Urban AI Engineer and PhD candidate at TU Delft with a background 
  in Transport Engineering. My work lives at the intersection of cities, human 
  perception, and deep learning — powered by a constant curiosity and a 
  drive to build creative solutions to real-world urban challenges.
twitter_username: FGarridoV
github_username: FGarridoV
minimal_mistakes_skin: mint
search: true
timezone: Europe/Amsterdam

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

# Outputting
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/

include:
  - _pages

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Author profile
author:
  name   : "Francisco Garrido-Valenzuela"
  avatar : "/assets/images/profile.jpg"  # You can change/remove this
  bio    : "Urban AI Engineer and PhD candidate at TU Delft"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/FGarridoV"
    - label: "Twitter"
      icon: "fab fa-twitter"
      url: "https://twitter.com/FGarridoV"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/FGarridoV"

# Footer links (simplified)
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-twitter"
      url: "https://twitter.com/FGarridoV"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/FGarridoV"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/FGarridoV"

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# Tag/category archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
